// Задача 6: Обработка ошибок в асинхронных функциях
// Задание: Модифицируйте функцию из Задачи 3 (fetchData(url)), чтобы она корректно обрабатывала исключения с использованием блока try/catch.
